#pragma once


#define MARIO_SMALL_BBOX_WIDTH  38
#define MARIO_SMALL_BBOX_HEIGHT 45


#define MARIO_BIG_BBOX_WIDTH  38
#define MARIO_BIG_BBOX_HEIGHT 81

#define TAIL_MARIO_BIG_BBOX_WIDTH  62
#define TAIL_MARIO_BIG_BBOX_HEIGHT 81

#define FIRE_MARIO_BBOX_WIDTH  45
#define FIRE_MARIO_BBOX_HEIGHT 81

#define MARIO_UNTOUCHABLE_TIME 5000

